src/academic/urls.py
from django.urls import path

from . import views

app_name = 'academic'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('talks/', views.TalksView.as_view(), name='talk_index'),
    path('talks/<int:pk>/', views.TalkDetailView.as_view(), name='talk_detail'),
    path('teaching/', views.TeachingView.as_view(), name='teaching'),
    path('awards_and_grants/', views.AwardsView.as_view(), name='awards'),
]

src/alexsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('home.urls')),
    path('academic/', include('academic.urls'))
]

src/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

src/academic/models.py
from django.db import models

class Talk(models.Model):
    title = models.CharField('Title', max_length=200)
    seminar_name = models.CharField('Seminar Name', max_length=200)
    location = models.CharField('Location', max_length=200)
    date_given = models.DateField('Date Given')
    abstract = models.TextField('Abstract', blank = True)
    
    def __str__(self):
        return self.title

class Paper(models.Model):
    title = models.CharField('Title',max_length=400)
    authors = models.TextField('Authors')
    link = models.URLField('Link', null = True)
    pub_date = models.DateField('Date Published')
    cite = models.CharField('Citation', max_length=500)
    
    def __str__(self):
        return self.title

class Award(models.Model):
    title = models.CharField('Title',max_length=400)
    date_obt = models.DateField('Date Obtained')
    text = models.TextField('Text on award', blank = True)
    organisation_name = models.CharField('Organisation', max_length=200)
    organisation_URL = models.URLField('Organisation URL', null=True)
    
    def __str__(self):
        return self.title
        
class Teaching(models.Model):
    
    class LevelChoices(models.TextChoices):
        GCSE = 'GC', 'GCSE'
        ALevel = 'AL', 'A-Level'
        Undergrad_year_1 = 'U1', 'Undergraduate Year 1'
        Undergrad_year_2 = 'U2', 'Undergraduate Year 2'
        Undergrad_year_3 = 'U3', 'Undergraduate Year 3'
        Masters = 'MA', 'Masters'
    
    level = models.CharField(
        max_length=2,
        choices = LevelChoices.choices,
        default = LevelChoices.Undergrad_year_1
    )
    
    class TypeChoices(models.TextChoices):
        Tutor = 'TU', 'Tutor'
        Supervisor = 'SU', 'Supervisor'
        ClassTeacher = 'CT', 'Class Teacher'
        Lecturer = 'LE', 'Lecturer'
    
    type = models.CharField(
        max_length=2,
        choices = TypeChoices.choices,
        default = TypeChoices.ClassTeacher
    )
    
    title = models.CharField('Title', max_length=200)
    organisation_name = models.CharField('Organisation', max_length=200)
    organisation_URL = models.URLField('Organisation URL')
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End date')
    description = models.TextField('Description')
    
    def __str__(self):
        return self.level + ' - ' + self.type + ': ' + self.title + ' for ' + self.organisation_name

src/home/models.py
from django.db import models

# Create your models here.

src/ideas/models.py
from django.db import models

class Idea(models.Model):
    title = models.CharField('Title', max_length=200)
    date_thought = models.DateField('Date Thought')
    Explaination = models.TextField('Explanation', blank = True)
	
    def __str__(self):
        return self.title

src/academic/views.py
from django.shortcuts import render
from django.views import generic

from .models import *

class IndexView(generic.ListView):
    template_name = "index.html"
    context_object_name = 'papers'
    
    def get_queryset(self):
        return Paper.objects.order_by('-pub_date')


class TalksView(generic.ListView):
    template_name = "talks_index.html"
    context_object_name = 'talks'
    
    def get_queryset(self):
        return Talk.objects.order_by('-date_given')

class TalkDetailView(generic.DetailView):
    model = Talk
    template_name = 'talk.html'

class TeachingView(generic.ListView):
    template_name = "teaching.html"
    context_object_name = 'teaching'
    
    def get_queryset(self):
        return Teaching.objects.order_by('-start_date')

class AwardsView(generic.ListView):
    template_name = "awards.html"
    context_object_name = 'awards'
    
    def get_queryset(self):
        return Award.objects.order_by('-date_obt')

src/home/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "home.html"

class AcademicView(TemplateView):
    template_name = "academic.html"

class ProjectsView(TemplateView):
    template_name = "projects.html"

src/ideas/views.py
from django.shortcuts import render

# Create your views here.

src/academic/templates/awards.html
{% extends "base_academic.html" %}

{% block page_content %}

<h1>Awards and Grants</h1>

<p>Add something about how much I love being awarded things.</p>

{% if awards %}

    <style>
    .vl {
        border-left: 3px solid black;
    }
    .v2 {
        border-left: 10px solid white;
    }
    .right {
        text-align: right;
    }
    </style>

	{% for award in awards %}
		<div class="row">
			<div class="col s2"><div class="right">{{ award.date_obt }}</div></div>
			<div class="col s10"><div class="vl"> <div class="v2"> <b>{{ award.title }}</b>, <a href={{award.organisation_URL}}>{{ award.organisation_name }}</a>.<br>
			{{award.text}} </div></div></div>
		</div>
    {% endfor %}
{% else %}
    <p>Be better at getting stuff.</p>
{% endif %}
{% endblock %}
	

src/academic/templates/base_academic.html
{% extends "base.html" %}

{% block bar_extension %}
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab"><a href={% url 'academic:talk_index'%}>Talks</a></li>
        <li class="tab"><a href={% url 'academic:teaching'%}>Teaching</a></li>
        <li class="tab"><a href={% url 'academic:awards'%}>Awards and Grants</a></li>
      </ul>
    </div>
{% endblock %}

src/academic/templates/index.html
{% extends "base_academic.html" %}

{% block page_content %}

<h1>Academic Life</h1>

<p>What you know shapes how you think, similarly for others. So contribute to the idea ecosystem by learning lots and spreading the good stuff!</p>

<p>I obtained a first class honours degree degree with a integrated masters in mathematics at the University of Warwick in 2011-15. My masters thesis supervised by <a href = https://warwick.ac.uk/fac/sci/maths/people/staff/dmitriy_rumynin/>Dmitriy Rumynin</a>, it was on the topic of 2-groups and their associated 2-Charracters. This thesis later became a paper, which can be found below. You can find all my module results here, the good, the bad and the humbling. I have various resources from my undergraduate studies in my dropbox and some other files associated with my teaching which can be found <a href= https://www.dropbox.com/home/Warwick%20University%20Math's>here</a>.</p>

<p>Next I studied a PhD in the University of Warwick supervised by <a href= https://homepages.warwick.ac.uk/~maslar/>Agelos Georgakopoulos</a>. Here I studied generalisations of groups and Cayley graphs, with a particular focus on graph theory.</p>

<p>I enjoy academic topics from Graph theory, Group theory, Geometric group Theory and other subjects that begin with G! I am also interested in interdisciplinary projects, be it in academic, commercial or policy. See my projects section for more details. The main thing I apply practically but want to understand more academically is machine learning. I want to apply more maths to real life, see my ideas section for more details about how I want to go about this.</p>

<p>I have always loved teaching, getting involved in it early and throwing myself in as much as possible. Find a list of all the teaching I did here.</p>

<h4>Publications</h4>

{% if papers %}
    <ul>
    {% for paper in papers %}
        <li style = "list-style-type:square">{{paper.authors}}. <a href= {{paper.link}}>{{ paper.title }}</a>. {{paper.cite}}, {{paper.pub_date}}.</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No papers are available.</p>
{% endif %}
{% endblock %}
	

src/academic/templates/talk.html
{% extends "base_academic.html" %}

{% block page_content %}

<h3> {{talk.title}} </h3>
{{talk.date_given}}: {{talk.location}}.

<p> {{talk.abstract}} </p>

{% endblock %}

src/academic/templates/talks_index.html
{% extends "base_academic.html" %}

{% block page_content %}

<h1>Talks</h1>

<p>Add something about how much I love talking here.</p>

{% if talks %}
    <style>
    .vl {
        border-left: 3px solid black;
    }
    .v2 {
        border-left: 10px solid white;
    }
    .right {
        text-align: right;
    }
    </style>
	
    {% for talk in talks %}
		<div class="row">
			<div class="col s2"><div class="right">{{talk.date_given}}</div></div>
			<div class="col s10"><div class="vl"> <div class="v2"> <b>{{talk.seminar_name}}, {{talk.location}}. </b>.<br>
			<a href="{% url 'academic:talk_detail' talk.id %}">{{talk.title}}</a></div></div></div>
		</div>
    {% endfor %}
{% else %}
    <p>No talks are available.</p>
{% endif %}
{% endblock %}
	

src/academic/templates/teaching.html
{% extends "base_academic.html" %}

{% block page_content %}

<h1>Teaching</h1>

<p>Add something about how much I love teaching here.</p>

{% if teaching %}

<!---    <p>Please choose how to sort my teaching.</p>

    <div class="row">
        <div class="col s4">
            <label>
                <input name="group1" type="radio" onclick="list_sort(0)" checked />
                <span>Date Started</span>
            </label>
        </div>
        <div class="col s4">
            <label>
                <input name="group1" type="radio" onclick="list_sort(1)"/>
                <span>Academic Level</span>
            </label>
        </div>
        <div class="col s4">
            <label>
                <input name="group1" type="radio" onclick="list_sort(2)"/>
                <span>Type</span>
            </label>
        </div>
    </div> 

    <p id="teaching_list">
            <ul>
            {% for course in teaching %}
                <li>{{ course.start_date }} - {{ course.end_date }} : <b>{{ course.title }} </b>.<br>
                {{ course.get_level_display }} {{ course.get_type_display }} at <a href={{ course.organisation_URL }}> {{ course.organisation_name }}</a></li>
            {% endfor %}
            </ul>
    </p> --->
    <style>
    .vl {
        border-left: 3px solid black;
    }
    .v2 {
        border-left: 10px solid white;
    }
    .right {
        text-align: right;
    }
    </style>
	
	{% for course in teaching %}
		<div class="row">
			<div class="col s2"><div class="right">{{ course.start_date }} - <br> {{ course.end_date }}</div></div>
			<div class="col s10"><div class="vl"><div class="v2"> <span style="display:inline-block; width: 10px;"></span> <b>{{ course.title }}</b>.<br>
			<span style="display:inline-block; width: 10px;"></span> {{ course.get_level_display }} {{ course.get_type_display }} at <a href={{ course.organisation_URL }}> {{ course.organisation_name }}</a></div></div></div>
		</div>
    {% endfor %}
    <!--- <script>
        function list_sort(val) {
            var text;
            if (val == 0) {
                text = "pic_bulboff.gif";
            } else if (val == 1) {
                text = "pic_bulbon.gif";
            } else {
                text = "blah";
            }
            document.getElementById('teaching_list').innerHTML = text;
        }
    </script> --->
{% else %}
    <p>No teaching is available.</p>
{% endif %}
{% endblock %}
	

src/home/templates/home.html
{% extends "base.html" %}

{% block page_content %}
<div class="row">
	<div class="col s8">
		<p>This is just proof I, Alex Wendland, exist. This site contains 
			information about me and acts as a database of my life experiences. 
			Also, I am using it to try out some ideas.</p>
        
		<p>I am a civil servant on the 
			<a href="https://www.faststream.gov.uk/">Science and Engeeneering 
			Fast Stream</a>. Previously, I did my PhD at the University of 
			Warwick under the supervision of 
			<a href="https://homepages.warwick.ac.uk/~maslar/"> Agelos 
			Georgakopoulos</a>.</p>
		
        <p>My interests are in programming and data. Infact I started this 
			website to develop my python, javascript, HTML and SQL skills a 
			little more. This shows my hand in the fact that I am a project 
			based learner.</p>
		
		<p>Next goal is to become more interesting so I have something more to 
			put here.</p>
	</div>
	<div class="col s4">
		<img src="static/img/Me.jpg" alt="Alex looking sexy">
	</div>	
</div>
{% endblock %}
	

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- MetaData-->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Alex Wendland</title>
	
    <!--- Materialise --->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
   
    
    <nav class="nav-extended">
        <div class="nav-wrapper">
            <a href={% url 'home:home'%} class="brand-logo">Alex Wendland</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href={% url 'academic:index'%}>Academic</a></li>
            </ul>
        </div>
        {% block bar_extension %}{% endblock %}
    </nav>
    
	<br>
	<div class="container">
	{% block page_content %}{% endblock %}
	</div>
    
    <!-- Materialise --->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>